services:
  # FastAPI Backend
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orion_erp
      - REDIS_URL=redis://localhost:6379
      - SECRET_KEY=development-secret-key-change-in-production
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # Note: Admin (Next.js) runs separately with npm run dev

  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orion_erp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # pgAdmin (Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@orion.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5051:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: